config/routes.rb
Rails.application.routes.draw do   
  get 'cart/index'
  
  resources :platillos

  resources :platillo_ordens

  resources :ordens

   root 'welcome#index'
   
   get '/pizza' => 'platillos#pizza', :as => 'pizza_forma'
   get '/pasta' => 'platillos#pasta', :as => 'pasta_forma'
   get '/postres' => 'platillos#postres', :as => 'postres_forma'
   get '/bebidas' => 'platillos#bebidas', :as => 'bebidas_forma'
   get '/menu' => 'platillos#menu', :as => 'menu_forma'
  get '/cart' => 'carts#index'
  post '/cart/show' => 'carts#show', :as => 'Carrito'
  resource :cart, only: [:show] do
    put 'add/:platillo.nombre', to: 'carts#add', as: :add_to
    put 'remove/:platillo.nombre', to: 'carts#remove', as: :remove_from
  end
   
   

end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

def show
end

app/models/orden.rb
class Orden < ActiveRecord::Base
end

app/models/platillo.rb
class Platillo < ActiveRecord::Base
   
      mount_uploader :image, ImageUploader
end

app/models/platillo_orden.rb
class PlatilloOrden < ActiveRecord::Base
 
   

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  protect_from_forgery 
  def index
  end
  
  def show
    if params[:cart].blank? 
      render "empty"
    else
      @cart = params["cart"]["orders"]
       render partial: "show"
    end
  end
end

app/controllers/ordens_controller.rb
class OrdensController < ApplicationController
  before_action :set_orden, only: [:show, :edit, :update, :destroy]

  # GET /ordens
  # GET /ordens.json
  def index
    @ordens = Orden.all
  end

  # GET /ordens/1
  # GET /ordens/1.json
  def show
  end

  # GET /ordens/new
  def new
    @orden = Orden.new
  end

  # GET /ordens/1/edit
  def edit
  end

  # POST /ordens
  # POST /ordens.json
  def create
    @orden = Orden.new(orden_params)

    respond_to do |format|
      if @orden.save
        format.html { redirect_to @orden, notice: 'Orden was successfully created.' }
        format.json { render :show, status: :created, location: @orden }
      else
        format.html { render :new }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordens/1
  # PATCH/PUT /ordens/1.json
  def update
    respond_to do |format|
      if @orden.update(orden_params)
        format.html { redirect_to @orden, notice: 'Orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @orden }
      else
        format.html { render :edit }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordens/1
  # DELETE /ordens/1.json
  def destroy
    @orden.destroy
    respond_to do |format|
      format.html { redirect_to ordens_url, notice: 'Orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orden
      @orden = Orden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orden_params
      params.require(:orden).permit(:total)
    end
end

app/controllers/platillo_ordens_controller.rb
class PlatilloOrdensController < ApplicationController
  before_action :set_platillo_orden, only: [:show, :edit, :update, :destroy]

  # GET /platillo_ordens
  # GET /platillo_ordens.json
  def index
    @platillo_ordens = PlatilloOrden.all
  end

  # GET /platillo_ordens/1
  # GET /platillo_ordens/1.json
  def show
  end

  # GET /platillo_ordens/new
  def new
    @platillo_orden = PlatilloOrden.new
  end

  # GET /platillo_ordens/1/edit
  def edit
  end

  # POST /platillo_ordens
  # POST /platillo_ordens.json
  def create
    @platillo_orden = PlatilloOrden.new(platillo_orden_params)

    respond_to do |format|
      if @platillo_orden.save
        format.html { redirect_to @platillo_orden, notice: 'Platillo orden was successfully created.' }
        format.json { render :show, status: :created, location: @platillo_orden }
      else
        format.html { render :new }
        format.json { render json: @platillo_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platillo_ordens/1
  # PATCH/PUT /platillo_ordens/1.json
  def update
    respond_to do |format|
      if @platillo_orden.update(platillo_orden_params)
        format.html { redirect_to @platillo_orden, notice: 'Platillo orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @platillo_orden }
      else
        format.html { render :edit }
        format.json { render json: @platillo_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platillo_ordens/1
  # DELETE /platillo_ordens/1.json
  def destroy
    @platillo_orden.destroy
    respond_to do |format|
      format.html { redirect_to platillo_ordens_url, notice: 'Platillo orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platillo_orden
      @platillo_orden = PlatilloOrden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platillo_orden_params
      params.require(:platillo_orden).permit(:idplatillo, :idorden)
    end
end

app/controllers/platillos_controller.rb
class PlatillosController < ApplicationController
  before_action :set_platillo, only: [:show, :edit, :update, :destroy]

  # GET /platillos
  # GET /platillos.json
  def index
  end

  def menu
     @platillos = Platillo.all
  end
   
  def pizza
      @platillos = Platillo.where("categoria = 'Pizza'")
  end
   
  def pasta
     @platillos = Platillo.where("categoria = 'Pasta'")
  end
   
   def postres
     @platillos = Platillo.where("categoria = 'Postres'")
  end
   
   def bebidas
     @platillos = Platillo.where("categoria = 'Bebidas'")
  end
   
  # GET /platillos/1
  # GET /platillos/1.json
  def show
  end

  # GET /platillos/new
  def new
    @platillo = Platillo.new
  end

  # GET /platillos/1/edit
  def edit
  end

   #GET /platillos/menu
   
  # POST /platillos
  # POST /platillos.json
  def create
    @platillo = Platillo.new(platillo_params)

    respond_to do |format|
      if @platillo.save
         
        format.html { redirect_to @platillo, notice: 'Platillo was successfully created.' }
        format.json { render :show, status: :created, location: @platillo }
      else
        format.html { render :new }
        format.json { render json: @platillo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platillos/1
  # PATCH/PUT /platillos/1.json
  def update
    respond_to do |format|
      if @platillo.update(platillo_params)
        format.html { redirect_to @platillo, notice: 'Platillo was successfully updated.' }
        format.json { render :show, status: :ok, location: @platillo }
      else
        format.html { render :edit }
        format.json { render json: @platillo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platillos/1
  # DELETE /platillos/1.json
  def destroy
    @platillo.destroy
    respond_to do |format|
      format.html { redirect_to platillos_url, notice: 'Platillo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platillo
      @platillo = Platillo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platillo_params
      params.require(:platillo).permit(:nombre, :precio, :descripcion, :categoria, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/helpers/platillo_ordens_helper.rb
module PlatilloOrdensHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_show.html.erb
<h1>Orden</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.each do |platillo| %>
      <tr>
        <td><%= platillo[1].fetch("nombre") %></td>
        <td><%=  platillo[1].fetch("precio") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<button onclick="swag()">Realizar Orden</button>

<script>
function swag() {
    
    alert("Su orden se realizo con exito!");
    localStorage.clear();
     window.location.href='/';
}
</script>

app/views/carts/empty.html.erb
<h1>Vacio</h1>
<div class="datagrid">

</div>
<br>
<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<script>
if(localStorage.getItem("cart") !== null){
  //la url tiene qye ser la url del controlador 
  //EL controlador tiene que mostrar el carrito con el objecto pasad en el nivel
  //orders.
  
  //Si no lo encunetra el dibujado del show.html.erb sera dependiendo del controlador
   //Dibujar una distinta vista que la show, ya que en show se incluye este JS, se estara            redijiendo asi mismo
  //El controlador a encontrar un objecto que se pase, ya sea POST o GET tendra que dibujar una       vista 
  //TL:DR se tendra 2 vistas , uno sin productos y otra con productos
  $.post( "/cart/show",{authenticity_token:"AGG2otysvsVx7HdCUxcZlAHPWu7CfRj2dQCHvi1QXBo=",
           cart: JSON.parse(localStorage["cart"])}, function( data ) {
     console.log(data);
             $("#cart-container").html(data);
});
  
}
</script>
<div id="cart-container"></div>
<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/carts/show.html.erb
<h1>Orden</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
    </tr>
  </thead>

  <tbody>
    <% @cart.each do |platillo| %>
      <tr>
        <td><%= platillo[1].fetch(image_url(:thumb).to_s) %></td>
        <td><%=  platillo[1].fetch("nombre") %></td> 
        <td><%= platillo[1].fetch("precio") %></td>
        <td><%=  platillo[1].fetch("descripcion") %></td>   
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calonise's Pizza</title>
  <%= stylesheet_link_tag 'platillo.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <!-- Header -->
      <div id = "header"> 
         <p> Calonise's Pizza

  <%= link_to cart_path do%>
    Mi Pedido
  <%end%>

         </p>
         
      </div>
      
<%= yield %>

    <!-- FOOTER -->
      <div id = "footer">
         <p>Created by Dynamic Solutions | Chihuahua, Chihuahua, MX | Last edit November 2014</p>
      </div>
   </body>

</html>

app/views/ordens/_form.html.erb
<%= form_for(@orden) do |f| %>
  <% if @orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orden.errors.count, "error") %> prohibited this orden from being saved:</h2>

      <ul>
      <% @orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ordens/edit.html.erb
<h1>Editing orden</h1>

<%= render 'form' %>

<%= link_to 'Show', @orden %> |
<%= link_to 'Back', ordens_path %>

app/views/ordens/index.html.erb
<h1>Menu!</h1>

<table>
  <thead>
    <tr>
      <th>Costo total de la orden: </th>
      
      
      
      
      <%= link_to 'New Orden', new_orden_path %>
   'no dar click'
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <tr>
      <td><img src="/imagenes/picon.jpg" alt="rss feed" /></td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/peperoni.jpg" alt="rss feed" /></td>
      <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/jamon.jpg" alt="rss feed" /></td>
      <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr> 
    
    <tr>  
    <td> <img src="/imagenes/champi.jpg" alt="rss feed" />
      <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>  

    
    <tr>
      <td><img src="/imagenes/sicon.jpg" alt="rss feed" /></td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/spa1.jpeg" alt="rss feed" /></td>
    <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/spa2.jpg" alt="rss feed" /></td>
    <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/micon.jpg" alt="rss feed" /></td>
    </tr>
    
    <tr>  
      <td><img src="/imagenes/nieve.jpg" alt="rss feed" /></td>
    <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/muffin.jpg" alt="rss feed" /></td>
  <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/bicon.jpg" alt="rss feed" /></td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/coca.jpg" alt="rss feed" /></td>
      <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/fanta.jpg" alt="rss feed" /></td>
      <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
    <tr>
      <td><img src="/imagenes/sprite.jpg" alt="rss feed" /></td>
      <td>"Aqui va el precio"</td>
      <td>"Aqui va la descripcion"</td>
      <td>"Aqui va donde se ingresa cantidad"</td>
    </tr>
    
  </tbody>
</table>

<br>


<%= link_to image_tag("/imagenes/confirmar.jpg", :border => 0, :alt => '', :title => ''), new_platillo_path, :class => 'dock-item' %>

app/views/ordens/new.html.erb
<h1>New orden</h1>

<%= render 'form' %>

<%= link_to 'Back', ordens_path %>

app/views/ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @orden.total %>
</p>

<%= link_to 'Edit', edit_orden_path(@orden) %> |
<%= link_to 'Back', ordens_path %>

app/views/platillo_ordens/_form.html.erb
<%= form_for(@platillo_orden) do |f| %>
  <% if @platillo_orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platillo_orden.errors.count, "error") %> prohibited this platillo_orden from being saved:</h2>

      <ul>
      <% @platillo_orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idplatillo %><br>
    <%= f.number_field :idplatillo %>
  </div>
  <div class="field">
    <%= f.label :idorden %><br>
    <%= f.number_field :idorden %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platillo_ordens/edit.html.erb
<h1>Editing platillo_orden</h1>

<%= render 'form' %>

<%= link_to 'Show', @platillo_orden %> |
<%= link_to 'Back', platillo_ordens_path %>

app/views/platillo_ordens/index.html.erb
<h1>Listing platillo_ordens</h1>

<table>
  <thead>
    <tr>
      <th>Idplatillo</th>
      <th>Idorden</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platillo_ordens.each do |platillo_orden| %>
      <tr>
        <td><%= platillo_orden.idplatillo %></td>
        <td><%= platillo_orden.idorden %></td>
        <td><%= link_to 'Show', platillo_orden %></td>
        <td><%= link_to 'Edit', edit_platillo_orden_path(platillo_orden) %></td>
        <td><%= link_to 'Destroy', platillo_orden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Platillo orden', new_platillo_orden_path %>

app/views/platillo_ordens/new.html.erb
<h1>New platillo_orden</h1>

<%= render 'form' %>

<%= link_to 'Back', platillo_ordens_path %>

app/views/platillo_ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idplatillo:</strong>
  <%= @platillo_orden.idplatillo %>
</p>

<p>
  <strong>Idorden:</strong>
  <%= @platillo_orden.idorden %>
</p>

<%= link_to 'Edit', edit_platillo_orden_path(@platillo_orden) %> |
<%= link_to 'Back', platillo_ordens_path %>

app/views/platillos/_form.html.erb
<%= form_for(@platillo) do |f| %>
  <% if @platillo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platillo.errors.count, "error") %> prohibited this platillo from being saved:</h2>

      <ul>
      <% @platillo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
     <%= f.select(:categoria, ['Pizza','Pasta','Postres','Bebidas']) %><p></p>
  </div>
  <div class="field">
    <%= f.file_field :image %><br><p></p>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platillos/bebidas.html.erb
//= require add_to_cart.js
<h1>Bebidas</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Agregar a Pedido</th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= image_tag platillo.image_url(:thumb).to_s%></td>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.precio %></td>
        <td><%= platillo.descripcion %></td>
        <td><%= link_to image_tag("/imagenes/carro.gif"), '#',
  :onclick => 'addToCart(JSON.parse(\''+platillo.to_json+'\'))' %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/platillos/edit.html.erb
<h1>Editing platillo</h1>

<%= render 'form' %>

<%= link_to 'Show', @platillo %> |
<%= link_to 'Back', platillos_path %>

app/views/platillos/index.html.erb
<div class = "right">
  <p><%= link_to image_tag("/imagenes/picon.jpg", :border => 0, :alt => '', :title => ''), pizza_forma_path, :class => 'dock-item', :id => 'perfil' %>
  <%= link_to image_tag("/imagenes/sicon.jpg", :border => 0, :alt => '', :title => ''), pasta_forma_path, :class => 'dock-item', :id => 'perfil' %>
  <%= link_to image_tag("/imagenes/micon.jpg", :border => 0, :alt => '', :title => ''), postres_forma_path, :class => 'dock-item', :id => 'perfil' %>
  <%= link_to image_tag("/imagenes/bicon.jpg", :border => 0, :alt => '', :title => ''), bebidas_forma_path, :class => 'dock-item', :id => 'perfil' %></p>
  <p><%= link_to image_tag("/imagenes/menu.gif", size: "200x100"), menu_forma_path, :class => 'dock-item', :id => 'perfil' %></p>
</div>

<p></p>
<p></p>

app/views/platillos/menu.html.erb
<h1>Listing platillos</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= image_tag platillo.image_url(:thumb).to_s%></td>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.precio %></td>
        <td><%= platillo.descripcion %></td>
        <td><%= platillo.categoria %></td>
        <td><%= link_to 'Show', platillo %></td>
        <td><%= link_to 'Edit', edit_platillo_path(platillo) %></td>
        <td><%= link_to 'Destroy', platillo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to image_tag("/imagenes/new.jpg", :border => 0, :alt => '', :title => ''), new_platillo_path, :class => 'dock-item' %>
<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/platillos/new.html.erb
<h1>New platillo</h1>

<%= render 'form' %>

<%= link_to 'Back', platillos_path %>

app/views/platillos/pasta.html.erb
//= require add_to_cart.js
<h1>Pastas</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Agregar a Pedido</th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= image_tag platillo.image_url(:thumb).to_s%></td>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.precio %></td>
        <td><%= platillo.descripcion %></td>
        <td><%= link_to image_tag("/imagenes/carro.gif"), '#',
  :onclick => 'addToCart(JSON.parse(\''+platillo.to_json+'\'))' %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/platillos/pizza.html.erb
//= require add_to_cart.js
<h1>Pizzas</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Agrear a la orden</th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= image_tag platillo.image_url(:thumb).to_s%></td>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.precio %></td>
        <td><%= platillo.descripcion %></td>
        <td><%= link_to image_tag("/imagenes/carro.gif"), '#',
  :onclick => 'addToCart(JSON.parse(\''+platillo.to_json+'\'))' %></td>     
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/platillos/postres.html.erb
//= require add_to_cart.js
<h1>Postres</h1>
<div class="datagrid">
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Agregar a Pedido</th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= image_tag platillo.image_url(:thumb).to_s%></td>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.precio %></td>
        <td><%= platillo.descripcion %></td>
        <td><%= link_to image_tag("/imagenes/carro.gif"), '#',
  :onclick => 'addToCart(JSON.parse(\''+platillo.to_json+'\'))' %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to image_tag("/imagenes/BackButton.png", size: "200x100"), platillos_path, :class => 'dock-item' %>

app/views/platillos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @platillo.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @platillo.precio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @platillo.descripcion %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @platillo.categoria %>
</p>

<p>
  <strong>Image:</strong>
   <%= image_tag @platillo.image_url(:detail).to_s%>
</p>

<%= link_to 'Edit', edit_platillo_path(@platillo) %> |
<%= link_to 'Back', platillos_path %>

app/views/welcome/index.html.erb
   
      <!-- Header -->
      
      <!-- LEFT -->
      <div class="left">
      <p><%= link_to image_tag("/imagenes/chefwelcome.png", :border => 0, :alt => '', :title => ''), platillos_path, :class => 'dock-item' %></p>
      </div>
      
     
   